---
- name: Ping - Check OS - Sample
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Test ping
      ansible.builtin.ping:
    - name: Check Dist Version
      shell: cat /etc/os-release
      register: response
    - debug: msg="{{ response.stdout }}"
