---
- name: Ping - Check OS - Sample
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Test ping
      ansible.builtin.ping:
    - name: Check OS
      ansible.builtin.shell: |
        cat /etc/os-release
