---
- name: Ping - Check OS - Sample
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Test ping
      ansible.builtin.ping:
    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_hostname }}", "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
