---
- name: Ping - Check OS - Sample
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Test ping
      ansible.builtin.ping:
    - name: Ping 2 package to 1.1.1.1
      ansible.builtin.shell: |
        ping 1.1.1.1 -c 2
      register: ping-result
    - name: ping 1.1.1.1 result
      debug:
        var: ping-result.stdout_lines
    - name: System details
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_hostname }}"
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
