---
- name: detect on /etc/sudoers
  hosts: all
  become: true
  tasks:
    - name: check file sudoers
      community.general.sudoers:
        name: check-sudoers
      register: sudoers_result

    - name: Xuất danh sách người dùng
      debug:
        var: sudoers_result.sudoers.users
