---
- name: detect on /etc/sudoers
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: get info host
      setup:
      register: host_info

    - name: export hostname
      debug:
        var: host_info.ansible_facts.hostname

