---
- name: lab-check-hostname
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:

    - name: export
      debug: msg="{{ item }}"
      with_items: 
      - "{{ ansible_hostname }}"
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
      when:
        - ansible_distribution == 'Ubuntu'
        - ansible_distribution_major_version == '20'
        - ansible_hostname.startswith('DC')

