---
- name: lab-check-hostname
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:

    - name: export
      debug:
        - var: ansible_hostname
      when:
        - ansible_hostname.startswith('DC')
#    - name: System details
#      debug: msg="{{ item }}"
#      with_items: 
#      - "{{ ansible_hostname }}"
#      - "{{ ansible_distribution }}"
#      - "{{ ansible_distribution_version }}"
#      - "{{ ansible_distribution_major_version }}"
#      local_action: 
#        module: copy 
#        content: "{{ item }}"
#        dest: ~/CheckOS.out
#      when:
#        - host_info.ansible_facts.hostname.startswith('DC')
