---
- name: Ping - Check OS - Sample
  hosts: all
  gather_facts: true
  tasks:
    - name: Test ping
      ansible.builtin.ping

    - name: Gather system details
      set_fact:
        system_details:
          ansible_hostname: "{{ ansible_hostname }}"
          ansible_distribution: "{{ ansible_distribution }}"
          ansible_distribution_version: "{{ ansible_distribution_version }}"
          ansible_distribution_major_version: "{{ ansible_distribution_major_version }}"

    - name: Save system details to file
      copy:
        content: "{{ system_details | to_nice_json }}"
        dest: /var/lib/awx/projects/log-run/CheckOS.out
