---
- name: Ping - Check OS - Sample
  hosts: all
  strategy: free
  gather_facts: true
  become: true
  tasks:
    - name: Test ping
      ansible.builtin.ping:

    - name: Gather system details
      debug:
        var: item
      with_items:
        - ansible_hostname
        - ansible_distribution
        - ansible_distribution_version
        - ansible_distribution_major_version
      register: system_details

    - name: Save system details to file
      copy:
        content: "{{ item.ansible_facts | to_nice_json }}"
        dest: /var/lib/awx/projects/log-run/CheckOS.out
      with_items: "{{ system_details.results }}"
