---
# tasks file for create-user
- name: Update new accounts
  user:
    name: "{{ item.name }}"
    password: "{{ item.password | password_hash('sha512') }}"
    append: yes
    state: present
    shell: /bin/bash
  with_items: "{{ user_details }}"

- name: Allow users to use sudo without password 
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item.name }}'
    line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
  with_items: "{{ sudoers }}"

- name: Add sudoers users to sudo group
  user:
    name: "{{ item.name }}"
    groups: sudo
    append: yes
  with_items: "{{ sudoers }}"

- name: Create a .ssh directory
  file:
    path: /home/{{ item.name }}/.ssh
    owner: "{{ item.name }}"
    group: "{{ item.group|default(item.name) }}"
    mode: 0700
    state: directory
  with_items: "{{ directory }}"

- name: Copy file key to server
  copy:
    src: authorized_keys
    dest: /home/{{ item.name }}/.ssh/
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items: "{{ directory }}"
